import json
import re
from datetime import datetime
from pathlib import Path

VERSION_FILE = Path("version.json")
VERSION_GENERATED = Path("version_generated.py")
PYPROJECT_FILE = Path("pyproject.toml")


def read_version() -> dict:
    if VERSION_FILE.exists():
        with VERSION_FILE.open() as f:
            return json.load(f)
    return {"major": 1, "minor": 0, "patch": 0, "build": 0, "build_date": "dev"}


def write_version(v: dict) -> None:
    with VERSION_FILE.open("w") as f:
        json.dump(v, f, indent=2)
    print(f"version.json -> {v['major']}.{v['minor']}.{v['patch']} (build {v['build']})")


def write_version_generated(v: dict) -> None:
    version_str = f"{v['major']}.{v['minor']}.{v['patch']}"
    build_str = str(v["build"])
    full_version = f"{version_str} ({build_str})"
    build_date = v.get("build_date", "dev")

    VERSION_GENERATED.write_text(
        "# Auto-generated by scripts/bump_version.py\n"
        f'APP_VERSION = "{version_str}"\n'
        f'APP_BUILD = "{build_str}"\n'
        f'APP_FULL_VERSION = "{full_version}"\n'
        f'APP_BUILD_DATE = "{build_date}"\n'
    )
    print(f"version_generated.py -> {full_version}")


def write_pyproject_version(v: dict) -> None:
    """Update the version field in pyproject.toml."""
    if not PYPROJECT_FILE.exists():
        return
    version_str = f"{v['major']}.{v['minor']}.{v['patch']}"
    content = PYPROJECT_FILE.read_text()
    new_content = re.sub(
        r'^(version\s*=\s*)"[^"]*"$',
        f'\\1"{version_str}"',
        content,
        count=1,
        flags=re.MULTILINE,
    )
    if new_content != content:
        PYPROJECT_FILE.write_text(new_content)
        print(f"pyproject.toml -> version {version_str}")


if __name__ == "__main__":
    v = read_version()
    v["build"] += 1
    v["build_date"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    write_version(v)
    write_version_generated(v)
    write_pyproject_version(v)